### ISSUE TITLE
component: Calendar

### ISSUE THREAD

**Issue by NautHnil** [anhskohbo/jekyll-for-frontend#10]
FILE
`src/include/components/calendar.html`

`src/_sass/layouts/sidebar.scss`

HTML

``` html
<div class="widget widget_calendar">
    <h2 class="widget-title h3">Calendar</h2>
    <div id="calendar_wrap" class="calendar_wrap">
        <table id="wp-calendar">
            <caption>July 2016</caption>
            <thead>
                <tr>
                    <th scope="col" title="Monday">M</th>
                    <th scope="col" title="Tuesday">T</th>
                    <th scope="col" title="Wednesday">W</th>
                    <th scope="col" title="Thursday">T</th>
                    <th scope="col" title="Friday">F</th>
                    <th scope="col" title="Saturday">S</th>
                    <th scope="col" title="Sunday">S</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="3" id="prev"><a href="#">« Jan</a></td>
                    <td class="pad">&nbsp;</td>
                    <td colspan="3" id="next" class="pad">&nbsp;</td>
                </tr>
            </tfoot>
            <tbody>
                <tr>
                    <td colspan="4" class="pad">&nbsp;</td>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td id="today">7</td>
                    <td>8</td>
                    <td>9</td>
                    <td>10</td>
                </tr>
                <tr>
                    <td>11</td>
                    <td>12</td>
                    <td>13</td>
                    <td>14</td>
                    <td>15</td>
                    <td>16</td>
                    <td>17</td>
                </tr>
                <tr>
                    <td>18</td>
                    <td>19</td>
                    <td>20</td>
                    <td>21</td>
                    <td>22</td>
                    <td>23</td>
                    <td>24</td>
                </tr>
                <tr>
                    <td>25</td>
                    <td>26</td>
                    <td>27</td>
                    <td>28</td>
                    <td>29</td>
                    <td>30</td>
                    <td>31</td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- /.calendar_wrap -->
</div>

```

SCSS

``` scss
//
// SIDEBAR LAYOUT
// ====================================================
.widget_calendar table {
  margin: 0;
  width: 100%;
  position: relative;

  #today {
    color: #fff;
    background: $brand-primary;
  }

  td, th {
    padding: 0;
    line-height: 3;
    text-align: center;
  }

  caption {
    color: #262e31;
    padding-top: 0;
    padding-bottom: 12px;
    margin-bottom: 5px;
    font-size: 16px;
    text-align: center;
    border-bottom: solid 1px #e1e8ec;
  }

  thead tr th {
    color: #262e31;
    font-weight: 400;
  }

  tbody {
    a {
      color: white;
      font-weight: 700;
      display: block;
      background-color: #86b5ac;

      &:hover, &:focus {
        color: white;
        background-color: #a6c8c2;
      }
    }

    tr td {
      font-size: 12px;
      color: lighten(black, 60%);
    }
  }

  tfoot {
    height: 0;
    display: inline-block;
    overflow: hidden;

    a {
      top: 7px;
      position: absolute;
      line-height: 1;
    }
  }

  #prev a {
    left: 0;
  }

  #next a {
    right: 0;
  }
}

```
