### ISSUE TITLE
component: Page Title

### ISSUE THREAD

**Issue by NautHnil** [anhskohbo/jekyll-for-frontend#6]
FILE
`src/include/components/page-title.html`

`src/_sass/layouts/_components/_page-title.scss`

Các biến cần khai báo khi dùng 1 file HTML đc include component: Page title

```

---
bg_page_title: page-title--bg-1
page_title_modifier: page-title--classic
page_title_tag: h1
page_title_tag_modifier: h1 <!-- Được truyền vào khi page_title_tag muốn dùng class nào khác -->

---
```

HTML

``` html
<section class="page-title {{ page.page_title_modifier }} {{ page.bg_page_title }}">
    <div class="page-title__info">
        <{{ page.page_title_tag }} class="{{ page.page_title_tag_modifier }} text-uppercase">{{ page.title }}</{{ page.page_title_tag }}>
        <ol class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li class="active">{{ page.title }}</li>
        </ol>
    </div>
</section>
<!-- /.page-title -->

```

SCSS

``` scss
/*
 * PAGE TITLE
 * ========================================
 */
.page-title {
  position: relative;
  padding: 150px 0;
  background-color: #fff;
  z-index: 1;
}

@for $bg from 1 through 10 {
  .page-title--bg-#{$bg} {
    background-image: url(../img-demo/pages-title/#{$bg}.jpg);
    background-repeat: no-repeat;
    background-position: center;
  }
}

.page-title--classic {
  &:before {
    content: "";

    @include overlay();

    z-index: -1;
  }

  * {
    color: white;
    text-shadow: 1px 1px 1px #333;
  }
}

.page-title__info {
  text-align: center;

  @include center();

  .breadcrumb {
    background: none;
    margin-bottom: 0;

    .active {
      color: white;
    }
  }
}

```
