### ISSUE TITLE
component: About me (Include: Blog Detail & Sidebar)

### ISSUE THREAD

**Issue by NautHnil** [anhskohbo/jekyll-for-frontend#8]
FILE
`src/include/components/about-me.html`

`src/_sass/layouts/_components/_about-me.scss`
`src/_sass/layouts/sidebar.scss`

HTML

``` html
<div class="about-me">
    <h3 class="about-me__title h4 text-uppercase">About me</h3>
    <div class="about-me__container clearfix">
        <div class="about-me__avatar">
            <img src="img-demo/avatars/5.png" alt="About me">
        </div>
        <div class="about-me__info">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            <div>Read more about me <a href="#" title="" class="text-uppercase">Here</a></div>
        </div>
    </div>
</div>
<!-- /.about-me -->

```

SCSS

``` scss
/*
 * ABOUT ME
 * ========================================
 */
.about-me {
  margin-bottom: 25px;
}

.about-me__title {
  margin-bottom: 25px;
}

.about-me__avatar {
  float: left;
  margin-right: 15px;

  @include media(">=xs") {
    margin-right: 30px;
  }

  img {
    width: 85px;
    height: 85px;
    border-radius: 100%;

    @include media(">=xs") {
      width: 110px;
      height: 110px;
    }
  }
}

.about-me__info a {
  color: $brand-primary;
  font-weight: 700;

  &:hover {
    text-decoration: underline;
  }
}

//
// SIDEBAR LAYOUT
// ====================================================
.widget_about_me {
  .about-me {
    text-align: center;
  }

  .about-me__title {
    text-transform: none;
    margin-bottom: 20px;

    @extend .h3;
  }

  .about-me__avatar {
    float: none;
    margin: 0 20px 25px;

    img {
      width: auto;
      height: auto;
      max-width: 100%;
    }
  }
}

```
