### ISSUE TITLE
component: Tags

### ISSUE THREAD

**Issue by NautHnil** [anhskohbo/jekyll-for-frontend#9]
FILE
`src/include/components/tags.html`

`src/_sass/layouts/sidebar.scss`

HTML

``` html
<div class="widget widget_tag_cloud">
    <h2 class="widget-title h3">Tags</h2>
    <div class="tagcloud">
        <a href="#" class="tag-link" title="">audio</a>
        <a href="#" class="tag-link" title="">Flower</a>
        <a href="#" class="tag-link" title="">gallery</a>
        <a href="#" class="tag-link" title="">left</a>
        <a href="#" class="tag-link" title="">My Friend</a>
        <a href="#" class="tag-link" title="">My Style</a>
        <a href="#" class="tag-link" title="">nosidebar</a>
        <a href="#" class="tag-link" title="">parallax</a>
        <a href="#" class="tag-link" title="">post format</a>
        <a href="#" class="tag-link" title="">right</a>
        <a href="#" class="tag-link" title="">sidebar</a>
        <a href="#" class="tag-link" title="">standard</a>
        <a href="#" class="tag-link" title="">Travel</a>
        <a href="#" class="tag-link" title="">video</a>
    </div>
    <!-- /.tagcloud -->
</div>

```

SCSS

``` scss
//
// SIDEBAR LAYOUT
// ====================================================
.widget_tag_cloud a {
  display: inline-block;
  font-size: 12px !important;
  color: #98a5a9;
  background-color: white;
  border: solid 1px #e1e8ec;
  padding: 7px 15px;
  margin-bottom: 10px;
  margin-right: 5px;
  transition: all .3s ease;
  height: inherit;
  line-height: inherit;

  &:hover, &:focus {
    border-color: $brand-primary;
    background-color: $brand-primary;
    color: #fff;
  }
}

```
